<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>apush-data-anal-FiveHive</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="apush-data-anal_files/libs/clipboard/clipboard.min.js"></script>
<script src="apush-data-anal_files/libs/quarto-html/quarto.js"></script>
<script src="apush-data-anal_files/libs/quarto-html/popper.min.js"></script>
<script src="apush-data-anal_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="apush-data-anal_files/libs/quarto-html/anchor.min.js"></script>
<link href="apush-data-anal_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="apush-data-anal_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="apush-data-anal_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="apush-data-anal_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="apush-data-anal_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">apush-data-anal-FiveHive</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mosaic)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pubtheme)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaflet)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gganimate)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(shiny)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>*This document is intended to complement the graphs, charts, and other</p>
<p>data analysis already done in the google spreadsheet by providing deeper</p>
<p>analyses and examining <em>relationships</em> between variables for APUSH data.</p>
<p>*Data is updated as of 05/31/2025.</p>
<section id="i.-reading-the-data" class="level1">
<h1>I. Reading the Data</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">'data/apush.csv'</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  ID Where.was.survey.found. Taken.APUSH.exam.
1  1     AP Students Discord               Yes
2  2     AP Students Discord               Yes
3  3     AP Students Discord               Yes
4  4     AP Students Discord               Yes
5  5     AP Students Discord               Yes
6  6     AP Students Discord               Yes
                                                        Other.AP.Courses
1                                                     Computer Science A
2                                                                       
3                                       English Language and Composition
4   Calculus BC, English Language and Composition, Environmental Science
5 English Language and Composition, Physics 1: Algebra Based, Statistics
6                                                                       
  Political.Stance Easy.to.Balance. See.you.soon. Taken.APUSH.
1               -3                5            NA           NA
2                3               NA            NA           NA
3               -4                1            NA           NA
4               NA                3            NA           NA
5               -4                6            NA           NA
6               -3                6            NA           NA
  Intend.to.take.APUSH. Taken.non.AP.equivalent.to.APUSH.
1                    NA                                NA
2                    NA                                NA
3                    NA                                NA
4                    NA                                NA
5                    NA                                NA
6                    NA                                NA
  Add.anything.you.d.like.to.mention.regarding.whether.you.ll.take.AP.United.States.History.in.the.future.
1                                                                                                       NA
2                                                                                                       NA
3                                                                                                       NA
4                                                                                                       NA
5                                                                                                       NA
6                                                                                                       NA
  Why.did.you.not.take.the.AP.exam.
1                                NA
2                                NA
3                                NA
4                                NA
5                                NA
6                                NA
                                                                                                                                                History.classes.before.APUSH
1                                                                                                                          Regular/Honors/Pre-AP World History and Geography
2 Regular/Honors/Pre-AP World History and Geography, Regular/Honors U.S. History, Regular/Honors/AP United States Goverment and Politics/Comparative Government and Politics
3                                                                                                                          Regular/Honors/Pre-AP World History and Geography
4                                                                                       Regular/Honors/Pre-AP World History and Geography, Regular/Honors/AP Human Geography
5                                                                     Regular/Honors/Pre-AP World History and Geography, Regular/Honors/AP Human Geography, AP World History
6                                                                                                                                                           AP World History
                                                                                                                                  Prerequisites
1 Regular/Honors/Pre-AP World History and Geography, Regular/Honors/AP United States Goverment and Politics/Comparative Government and Politics
2                                                                                             Regular/Honors/Pre-AP World History and Geography
3                                                                                             Regular/Honors/Pre-AP World History and Geography
4                                                                                             Regular/Honors/Pre-AP World History and Geography
5                                                          Regular/Honors/Pre-AP World History and Geography, Regular/Honors/AP Human Geography
6                                                                                                                   Regular/Honors U.S. History
  Expected.difficulty.of.course
1                             9
2                             5
3                             7
4                             8
5                             8
6                             5
                                                Expected.difficult.things
1                                           Work load and writing so much
2                                                          Content amount
3 Remembering the dates of events and how each event affects one another.
4          knowing all the content and staying interested in the material
5                                                            the workload
6                                                                        
                                                       Expected.easy.things
1                                                     Comprehending content
2                                                                 The tests
3                                                    Early American history
4 understanding what questions were asking, as i had already taken ap world
5                                                               the content
6                                                                          
  Were.those.feelings.accurate.
1                           Yes
2                            No
3                           Yes
4                           Yes
5                            No
6                            No
                                                               Misjudged.difficulty
1                                                         Difficulty of the writing
2                                                                     Content depth
3 I thought the multiple choice portion was going to be more difficult than it was.
4                                                                              LEQs
5                       the content is super in depth and i severely misjudged that
6                                                                                  
  Grade.Level College.Board.FRQs College.Board.Course.and.Exam.Description
1   Sophomore         Didn't use                                Didn't use
2      Junior         Used-Liked                             Used-Disliked
3      Junior         Used-Liked                                Didn't use
4      Junior         Used-Liked                         Used-Very Helpful
5      Junior         Used-Liked                             Used-Mediocre
6   Sophomore         Didn't use                                Didn't use
  AP.Daily.Practice.Sessions..videos.released.in.April.by.CB.
1                                                  Didn't use
2                                                  Didn't use
3                                                  Didn't use
4                                                  Didn't use
5                                                  Didn't use
6                                                  Didn't use
  AP.Classroom.Topic.Videos AP.Classroom.Questions.Progress.Checks
1                Used-Liked                      Used-Very Helpful
2                Didn't use                             Used-Liked
3             Used-Disliked                          Used-Mediocre
4                Didn't use                             Used-Liked
5                Didn't use                             Didn't use
6                Didn't use                             Didn't use
  AP.Students.Reddit.Discord Khan.Academy Content.Textbooks
1          Used-Very Helpful   Used-Liked        Didn't use
2                 Didn't use   Didn't use     Used-Disliked
3                 Didn't use   Didn't use        Didn't use
4                 Didn't use   Didn't use     Used-Mediocre
5              Used-Mediocre   Didn't use        Didn't use
6                 Didn't use   Didn't use     Used-Mediocre
  Review.Textbooks..Princeton..Barrons..etc.. Heimler.s.History
1                                  Didn't use     Used-Mediocre
2                                  Didn't use     Used-Disliked
3                                  Didn't use        Didn't use
4                                  Didn't use Used-Very Helpful
5                                  Didn't use Used-Very Helpful
6                                  Didn't use Used-Very Helpful
  Gilder.Lehrman.Institute TomRichey.net Marco.Learning  Albert.io      Chegg
1               Didn't use    Didn't use     Didn't use Didn't use Didn't use
2               Didn't use    Didn't use     Didn't use Didn't use Didn't use
3               Didn't use    Didn't use     Didn't use Didn't use Didn't use
4               Didn't use    Didn't use     Didn't use Didn't use Didn't use
5               Didn't use    Didn't use     Didn't use Used-Liked Didn't use
6               Didn't use    Didn't use     Didn't use Didn't use Didn't use
            Quizlet      Fiveable Anti.Social.Studies
1        Didn't use Used-Mediocre          Didn't use
2        Used-Liked    Didn't use          Didn't use
3 Used-Very Helpful    Didn't use          Didn't use
4 Used-Very Helpful    Didn't use          Didn't use
5        Used-Liked    Didn't use          Didn't use
6        Didn't use    Didn't use          Didn't use
                                                                                                                                                                                                                                                                 Elaborate.on.resources
1                                                                                                                                                                                                                                                          progress checks are the best
2                                                                                                                                                                                                                                                                                      
3                                                                         The problems provided by college board were harder than the ones on the AP test this year, likely because the ones on the college board website encompassed a larger portion of US history than the test did.
4 i used the american pageant textbook for finding vocab, which i then used quizlet to study. the CED was helpful in letting me understand what i needed to study for a unit specifically. heimler is just the GOAT of history and explains it SO well, so he was often my study buddy.
5                                                                                         Heimler’s history is really really good, i’ve used it two years in a row and it has not failed. I used CrackAp.com for practice problems which were quite similar to the ones on the ap exam.
6                                                                                                                                                                                                                                                                                      
  How.well.prepared.did.you.feel.for.your.exam
1                                            4
2                                            7
3                                            7
4                                            8
5                                            7
6                                            4
  What.did.you.feel.well.prepared.for.   What.did.you.feel.ill.prepared.for.
1                             Unit 6-9          Units from early in the year
2                                 MCQs FRQs, contemp history (post cold war)
3    The writing portions of the test.                  The multiple choice.
4                             SAQ, MCQ                                   LEQ
5                  The LEQ and the SAQ                               the DBQ
6                                                                           
  Accurate.reflection.during.test. X.Unit.1..1491.1607. X.Unit.2..1607.1754.
1                               No                                       3rd
2                               No                                       1st
3                               No                                          
4                              Yes                                          
5                               No                                          
6                              Yes                                          
  X.Unit.3..1754.1800. X.Unit.4..1800.1848. X.Unit.5..1844.1877.
1                  1st                  2nd                     
2                                       2nd                     
3                                       1st                  2nd
4                                       2nd                     
5                                                               
6                                       3rd                  2nd
  X.Unit.6..1865.1898. X.Unit.7..1890.1945. X.Unit.8..1945.1980.
1                                                               
2                  3rd                                          
3                  3rd                                          
4                  3rd                  1st                     
5                  1st                  2nd                  3rd
6                                                            1st
  X.Unit.9..1980.Present.
1                        
2                        
3                        
4                        
5                        
6                        
                                                                                                               Why.were.those.units.hard.
1        A lot of the terminology and content was different from modern days so it was more difficult to comprehend than the modern units
2 Too much content, Difficult to link events together, Interpreting primary source documents, The other units were just relatively easier
3                                                                                             The other units were just relatively easier
4                                                                           Too much content, The other units were just relatively easier
5                                                            Too much content, Difficult to link events together, Didn't review it enough
6                                                                           Too much content, The other units were just relatively easier
  X.Unit.1..1491.1607..1 X.Unit.2..1607.1754..1 X.Unit.3..1754.1800..1
1                                                                     
2                                                                  1st
3                                           1st                    2nd
4                    1st                                           3rd
5                    1st                    2nd                    3rd
6                    1st                    2nd                    3rd
  X.Unit.4..1800.1848..1 X.Unit.5..1844.1877..1 X.Unit.6..1865.1898..1
1                                                                  2nd
2                                           2nd                       
3                                                                     
4                                           2nd                       
5                                                                     
6                                                                     
  X.Unit.7..1890.1945..1 X.Unit.8..1945.1980..1 X.Unit.9..1980.Present..1
1                                           3rd                       1st
2                                                                     3rd
3                    3rd                                                 
4                                                                        
5                                                                        
6                                                                        
                                                                                                                                                                                                                             Why.were.those.units.easy.
1                                               Less content, Easier to link events together, Easier to connect to historical themes, Easier to apply historical thinking skills (change, continuity, etc), The other units were just relatively harder
2 Less content, Easier to link events together, Easier to interpret primary source documents, Easier to connect to historical themes, Easier to apply historical thinking skills (change, continuity, etc), The other units were just relatively harder
3                                                                                             Easier to connect to historical themes, Easier to apply historical thinking skills (change, continuity, etc), The other units were just relatively harder
4                                               Less content, Easier to link events together, Easier to connect to historical themes, Easier to apply historical thinking skills (change, continuity, etc), The other units were just relatively harder
5                                                                                                                     Less content, Easier to link events together, Easier to connect to historical themes, The other units were just relatively harder
6                                                                                                                                                                                                                                     Previous learning
  American...National.Identity Work..Exchange....Technology
1                          8th                          1st
2                          6th                          1st
3                          8th                          7th
4                          3rd                          4th
5                          7th                          5th
6                          5th                          6th
  Geography...Environment Immigration...Settlement Politics...Power
1                     7th                      6th              5th
2                     2nd                      5th              4th
3                     1st                      6th              5th
4                     2nd                      1st              7th
5                     2nd                      4th              1st
6                     7th                      1st              2nd
  America.in.the.World American...Regional.Culture Social.Structures
1                  4th                         3rd               2nd
2                  7th                         8th               3rd
3                  4th                         3rd               2nd
4                  8th                         6th               5th
5                  6th                         8th               3rd
6                  8th                         3rd               4th
                                                                                                                                                                                                                                                              Explain.your.ranking.of.the.course.themes.by.difficulty.
1                                                                                                                                                                                                                        national identity is just a pretty obscure topic, the rest are all pretty close in difficulty
2                                                                                                                                                                                                                                                                                                                  N/A
3                                                                                                                                                                                                                                 I struggle with geography, but the other themes are relatively easy to get ahold of.
4 some themes, specifically politics and power and social structures, were present in AP World, so i was good at looking for those. i also found america in the world easier because after a certain point, our position and involvement in the world just snowballs and becomes greater and greater with every action
5                                                                                                                                                                                                                             They are very subjective to my perspective of history and understanding of the content. 
6                                                                                                                                                                                                                                           Because of how much experience i had with those topics in previous classes
  Weeks.per.unit How.did.you.feel.about.the.pace.of.the.course.
1             NA                                              7
2              6                                              8
3              2                                              8
4              3                                              5
5              8                                              7
6             NA                                              8
  Time.management.during.exam
1                           9
2                           3
3                          10
4                           7
5                           5
6                           3
  What.did.you.score.on.the.AP.United.States.History.exam.
1                                                        5
2                                                        4
3                                                        4
4                                                        4
5                                                        4
6                                                        3
  How.did.you.primarily.prepare.for.the.exam.
1                    Course at my high school
2                    Course at my high school
3                    Course at my high school
4                    Course at my high school
5                    Course at my high school
6                    Course at my high school
  How.easy.is.it.to.self.study.AP.United.States.History.
1                                                     NA
2                                                     NA
3                                                     NA
4                                                     NA
5                                                     NA
6                                                     NA
  What.elements.of.the.course.did.you.find.easy.to.self.study.
1                                                             
2                                                             
3                                                             
4                                                             
5                                                             
6                                                             
  What.elements.of.the.course.did.you.find.difficult.to.self.study.
1                                                                  
2                                                                  
3                                                                  
4                                                                  
5                                                                  
6                                                                  
  How.many.weeks.did.you.spend.learning.for.the.AP.United.States.History.exam.
1                                                                           NA
2                                                                           NA
3                                                                           NA
4                                                                           NA
5                                                                           NA
6                                                                           NA
  How.many.hours.a.week.did.you.dedicate.to.self.studying.AP.United.States.History.
1                                                                                NA
2                                                                                NA
3                                                                                NA
4                                                                                NA
5                                                                                NA
6                                                                                NA
  How.many.weeks.did.you.spend.reviewing..not.learning..for.the.AP.United.States.History.exam.as.you.self.studied.
1                                                                                                               NA
2                                                                                                               NA
3                                                                                                               NA
4                                                                                                               NA
5                                                                                                               NA
6                                                                                                               NA
  If.you.self.studied..what.would.your.advice.be.for.others.who.wish.to.do.the.same.
1                                                                                   
2                                                                                   
3                                                                                   
4                                                                                   
5                                                                                   
6                                                                                   
  Rate.the.quality.of.your.teacher.s.preparation.for.the.exam.
1                                                            9
2                                                            4
3                                                            8
4                                                            8
5                                                            7
6                                                            6
                                                                                                                                                       Good.teacher.traits
1                                                                                                                                                                         
2                                                                                                                               Pacing helped us have ample time to review
3                                                                                                                  He helped solidify concepts and reviewed material well.
4            the biggest thing was doing units not as collegeboard made them, but based on different events and themes that allowed for easier consumption of information.
5 He explained things really well and gave a lot of homework which seemed bad in the moment but it established strong levels of understanding for the content on the exam.
6                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                         Bad.teacher.traits
1                                                                                                                                                                                                                                                                                                                                                                          
2                                                                                                                                                                                                                                                                                                                        Not focused on the exam, wasn't helpful for review
3                                                                                                                                                                                                                                                                           There could have been more of a focus on the essay portions and the middle parts of US history.
4 the aforementioned unit separation did make my mental timeline a little fuzzy. events would happen in the same timeframe, but because they were in different units, my brain wouldn’t let me associate them with each other (for example, we split one period into the cold war and civil rights. the two units made it difficult to remember they were at the same time)
5                                                                                                                                                                                                                            The very rushed nature of the class which really wasn’t my teacher’s fault but it definitely hindered my depth of understanding for the class.
6                                                                                                                                                                                                                                                                                                                                                                          
  Hours.week..not.before.exam. Weeks.at.end.of.year.reviewing
1                          1.0                              5
2                          8.0                              6
3                          2.0                              2
4                          1.5                              2
5                          5.0                              5
6                          2.0                              2
  How.many.weeks..at.the.end.of.the.year..did.you.dedicate.to.studying.for.the.AP.United.States.History.exam.outside.of.the.classroom.
1                                                                                                                                    1
2                                                                                                                                    8
3                                                                                                                                    0
4                                                                                                                                    1
5                                                                                                                                   20
6                                                                                                                                    3
  Did.you.find.it.necessary.to.seek.additional.help.outside.of.your.regular.class.time..If.so..how.did.you.access.this.help.
1                                                                                                                           
2                                                                                                                      Peers
3                                                                                                                         No
4                                                                                                                         no
5                                                                                                   extra help w my teacher 
6                                                                                                                           
  How.hard.is.AP.United.States.History. X.Multiple.Choice.Questions..MCQs..
1                                     5                                   1
2                                     8                                   1
3                                     1                                   1
4                                     5                                   2
5                                     9                                   3
6                                     8                                   1
  X.Short.Answer.Questions..SAQs.. X.Document.Based.Question..DBQ..
1                                2                                4
2                                3                                5
3                                1                                2
4                                2                                3
5                                2                                4
6                                4                                3
  X.Long.Essay.Question..LEQ..
1                            2
2                            4
3                            3
4                            3
5                            4
6                            5
  Difficult.to.identify.appropriate.thinking.skill.
1                                                 5
2                                                 7
3                                                 1
4                                                 1
5                                                 7
6                                                 3
  Is.APUSH.more.memorization.or.skill.based.thinking.skills.and.reasoning.process..
1                                                                                 1
2                                                                                -3
3                                                                                -3
4                                                                                 1
5                                                                                 2
6                                                                                -2
  Is.AP.United.States.History.fun.
1                               No
2                               No
3                              Yes
4                              Yes
5                              Yes
6                               No
  X.THEME.1..AMERICAN.AND.NATIONAL.IDENTITY..NAT..
1                                                2
2                                                3
3                                                3
4                                                4
5                                                2
6                                                1
  X..THEME.2..WORK..EXCHANGE..AND.TECHNOLOGY..WXT..
1                                                 5
2                                                 2
3                                                 3
4                                                 2
5                                                 3
6                                                 1
  X.THEME.3..GEOGRAPHY.AND.THE.ENVIRONMENT..GEO..
1                                               2
2                                               2
3                                               1
4                                               2
5                                               4
6                                               1
  X.THEME.4..MIGRATION.AND.SETTLEMENT..MIG..
1                                          4
2                                          4
3                                          5
4                                          2
5                                          1
6                                          1
  X.THEME.5..POLITICS.AND.POWER..PCE.. X.THEME.6..AMERICA.IN.THE.WORLD..WOR...
1                                    5                                       5
2                                    3                                       4
3                                    4                                       1
4                                    4                                       5
5                                    3                                       5
6                                    1                                       1
  X.THEME.7..AMERICAN.AND.REGIONAL.CULTURE..ARC..
1                                               5
2                                               2
3                                               1
4                                               3
5                                               5
6                                               1
  X.THEME.8..SOCIAL.STRUCTURES..SOC.. X.Developments.and.Processes.
1                                   5                             1
2                                   4                             3
3                                   5                             4
4                                   3                             2
5                                   4                             2
6                                   1                             1
  X.Sourcing.and.Situation. X.Claims.and.Evidence.in.sources.
1                         2                                 3
2                         2                                 3
3                         1                                 1
4                         3                                 3
5                         5                                 3
6                         2                                 4
  X.Contextualization. X.Making.Connections. X.Argumentation. X.Comparison.
1                    1                     3                3             1
2                    3                     3                4             3
3                    3                     4                1             1
4                    1                     3                2             1
5                    1                     1                4             4
6                    2                     2                4             3
  X.Causation. Difficulty.of..Continuity.and.Change.
1            4                                     1
2            3                                     4
3            2                                     3
4            1                                     3
5            5                                     3
6            2                                     4
  How.much.did.World.help.with.APUSH How.much.did.Euro.help.with.APUSH
1                                                                     
2                                                                     
3                    Helped a little                                  
4                       Helped a lot                                  
5                       Helped a lot                                  
6                    Helped a little                                  
  Comparing.World.to.APUSH Comparing.Euro.to.APUSH Easier.to.gain.points.now.
1            Not taken yet           Not taken yet                          2
2            Not taken yet           Not taken yet                          4
3        Harder than APUSH           Not taken yet                          5
4        Easier than APUSH           Not taken yet                          1
5        Easier than APUSH           Not taken yet                          5
6        Easier than APUSH           Not taken yet                          3
                        Study.Groups What.year.did.you.take.APUSH.
1 I didn't use study groups/sessions             May 2024 or after
2                                 No             May 2024 or after
3 I didn't use study groups/sessions             May 2024 or after
4 I didn't use study groups/sessions             May 2024 or after
5                                 No             May 2024 or after
6 I didn't use study groups/sessions             May 2024 or after
                                                                                             Appealing.Units.Topics
1                                                                                                                  
2                                                                                                                  
3                                                                                                                  
4 cold war, gilded age/whatever the era of like meat packing and calling out big oil is (i can’t remember the name)
5                                                                                      unit 9 was most interesting 
6                                                                                                                  
                                                                                                                                                                                                                                                                                                                       Words.of.Wisdom
1                                                                                                                                                                      You don't have to dedicate entire days to the class or stay up late studying. If you just study a little bit each day and stay consistent, then you'll do fine.
2                                                                                                                                                                                                                                                                                                                                     
3                                                                                                                                                                                                                                                                     Review your notes and continuously connect events to each other.
4 Do not try to be too fancy with your writing. This is an AP history class, not your honors english class where you had to write beautifully. With the new rubric, you can easily get the complexity point without being too fancy, and the fancy writing will just make it more likely that you contradict yourself and lose points.
5                                                                                                                                                                                      Please study routinely and try to retain the information you learn throughout the year, instead of one massive cramming session at the very end
6                                                                                                                                                                                                                                                                                                                                     
  DBQ..Second.Evidence.Point DBQ...Analysis.Point DBQ...Complexity
1                          4                    4                5
2                          5                    4                4
3                          3                    3                3
4                          4                    4                5
5                          2                    1                4
6                          3                    3                4
  LEQ...Evidence.Point LEQ...Complexity.Point
1                    4                      5
2                    4                      4
3                    3                      3
4                    3                      5
5                    2                      3
6                    3                      2
  Different.score.if.taken.recently. Did.you.use.AI.as.a.learning.tool.
1                                 NA                                Yes
2                                 NA                                Yes
3                                 NA                                Yes
4                                 NA                                 No
5                                 NA                                 No
6                                 NA                                 No
  Which.AI.model.did.you.use. How.useful.was.it.on.a.scale.of.1.to.10.
1                     ChatGPT                                        3
2                     ChatGPT                                        6
3         ChatGPT, NotebookLM                                        8
4                                                                   NA
5                                                                   NA
6                                                                   NA
                                            What.was.AI.good.at.explaining.
1                                                                          
2                                                                          
3 It was good at contextualizing events and connecting them to one another.
4                                                                          
5                                                                          
6                                                                          
                                  Where.was.it.lackluster.
1                                                         
2             Lack of connection to APUSH-specific content
3 Responses were often way more information than I needed.
4                                                         
5                                                         
6                                                         
  Taken.higher.level.studies. Smooth.transition.to.higher.level.studies.
1                          No                                         NA
2                          No                                         NA
3                          No                                         NA
4                          No                                         NA
5                          No                                         NA
6                          No                                         NA
  Explain.the.above.response.
1                            
2                            
3                            
4                            
5                            
6                            </code></pre>
</div>
</div>
</section>
<section id="ii.-cleaning-the-data" class="level1">
<h1>II. Cleaning the Data</h1>
<p>•Initial examination suggests the data is readable enough to not demand any</p>
<p>significant cleaning at the very beginning.</p>
<p>•Instead, we jump right into the next steps and clean <em>as needed</em></p>
<p>(our end product is not the data set but rather a document that</p>
<p>cleanly summarizes key findings from the data analysis, as well as other info).</p>
<p>•For convenience and readability, we will still do some of our</p>
<p>necessary cleaning here that we would’ve done later on.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming columns</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">=</span> d <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">SCORE =</span> What.did.you.score.on.the.AP.United.States.History.exam.) <span class="sc">%&gt;%</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">class =</span> Grade.Level) <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">teach.prep =</span> Rate.the.quality.of.your.teacher.s.preparation.for.the.exam.) <span class="sc">%&gt;%</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">overall.prep =</span> </span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>           How.well.prepared.did.you.feel.for.your.exam) <span class="sc">%&gt;%</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">overall.diff =</span> How.hard.is.AP.United.States.History.) <span class="sc">%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">other.courses =</span> Other.AP.Courses) <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">expected.diff =</span> Expected.difficulty.of.course) <span class="sc">%&gt;%</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">enjoy =</span> Is.AP.United.States.History.fun.) <span class="sc">%&gt;%</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">ai =</span> Did.you.use.AI.as.a.learning.tool.) <span class="sc">%&gt;%</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme1 =</span> X.THEME.<span class="dv">1</span>..AMERICAN.AND.NATIONAL.IDENTITY..NAT..) <span class="sc">%&gt;%</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme2 =</span> X..THEME.<span class="dv">2</span>..WORK..EXCHANGE..AND.TECHNOLOGY..WXT..) <span class="sc">%&gt;%</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme3 =</span> X.THEME.<span class="dv">3</span>..GEOGRAPHY.AND.THE.ENVIRONMENT..GEO..) <span class="sc">%&gt;%</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme4 =</span> X.THEME.<span class="dv">4</span>..MIGRATION.AND.SETTLEMENT..MIG..) <span class="sc">%&gt;%</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme5 =</span> X.THEME.<span class="dv">5</span>..POLITICS.AND.POWER..PCE..) <span class="sc">%&gt;%</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme6 =</span> X.THEME.<span class="dv">6</span>..AMERICA.IN.THE.WORLD..WOR...) <span class="sc">%&gt;%</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme7 =</span> X.THEME.<span class="dv">7</span>..AMERICAN.AND.REGIONAL.CULTURE..ARC..) <span class="sc">%&gt;%</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">theme8 =</span> X.THEME.<span class="dv">8</span>..SOCIAL.STRUCTURES..SOC..) <span class="sc">%&gt;%</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Developments.and.Processes =</span> X.Developments.and.Processes.) <span class="sc">%&gt;%</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Sourcing.and.Citation =</span> X.Sourcing.and.Situation.) <span class="sc">%&gt;%</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Claim.and.Evidence.in.Sources =</span> X.Claims.and.Evidence.in.sources.) <span class="sc">%&gt;%</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Contextualization =</span> X.Contextualization.) <span class="sc">%&gt;%</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Making.Connections =</span> X.Making.Connections.) <span class="sc">%&gt;%</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Argumentation =</span> X.Argumentation.)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="iii.-visualization-and-analysis" class="level1">
<h1>III. Visualization and Analysis</h1>
<p>•Graphs and charts have already been made for most questions</p>
<p>in the spreadsheet; however, we may still be interested in seeing</p>
<p>if there are possible relationships.</p>
<p>•Example: We might want to look at the distribution of scores for each</p>
<p>grade level.</p>
<p>•Motivation: Some people say that you should only take APUSH when you’re a</p>
<p>junior or senior. But is that really true? Could it really be that how older one is</p>
<p>(to graduating) has some effects on the exam score?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>g <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(class, SCORE)) <span class="sc">+</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Looks like the only groups that have multiple values of score are juniors</p>
<p>and sophomores. The rest are concentrated on only one value. This likely</p>
<p>indicates not as many responses in these groups as for juniors</p>
<p>and sophomores. We can take a look at these two individually and compare</p>
<p>their distribution of scores:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Sophomores</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>d2_sopho <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(class <span class="sc">==</span> <span class="st">'Sophomore'</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>g_sopho <span class="ot">=</span> d2_sopho <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>SCORE)) <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Exam Scores (Sophomores)"</span>,</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Score"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>g_sopho</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>d2_junior <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(class <span class="sc">==</span> <span class="st">'Junior'</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>g_junior <span class="ot">=</span> d2_junior <span class="sc">%&gt;%</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>SCORE)) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">3</span>) <span class="sc">+</span> </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Histogram of Exam Scores (Juniors)"</span>,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">xlab =</span> <span class="st">"Score"</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">ylab =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>g_junior</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>It does appear that juniors have a higher frequency of better scores, but</p>
<p>this might this be due to the larger sample size (more juniors happen to have</p>
<p>responded to the survey)?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2_junior<span class="sc">$</span>SCORE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 45</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2_sopho<span class="sc">$</span>SCORE)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24</code></pre>
</div>
</div>
<p>Let’s take a look at percentages, which is more fair when comparing</p>
<p>count data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"% of 'good' scores for juniors (4/5): "</span>, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(d2_junior<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> d2_junior<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">/</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">length</span>(d2_junior<span class="sc">$</span>SCORE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "% of 'good' scores for juniors (4/5):  0.911111111111111"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"% of 'good' scores for sophomores (4/5): "</span>, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(d2_sopho<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">4</span> <span class="sc">|</span> d2_sopho<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">/</span> </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">length</span>(d2_sopho<span class="sc">$</span>SCORE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "% of 'good' scores for sophomores (4/5):  0.875"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"% of max scores for juniors (5): "</span>, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(d2_junior<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">/</span> <span class="fu">length</span>(d2_junior<span class="sc">$</span>SCORE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "% of max scores for juniors (5):  0.533333333333333"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"% of max scores for sophomores (5): "</span>, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>      <span class="fu">sum</span>(d2_sopho<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">/</span> <span class="fu">length</span>(d2_sopho<span class="sc">$</span>SCORE))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "% of max scores for sophomores (5):  0.708333333333333"</code></pre>
</div>
</div>
<p>Something interesting just happened. When we look at 4s <em>and</em> 5s, we see</p>
<p>that juniors slightly edge out, but when just looking at 5s, the maximum</p>
<p>possible score reported on the exam, there is a significant proportion of</p>
<p>sophomores vs.&nbsp;juniors! Why might this be? It makes sense if we consider</p>
<p>that those who take the course/exam as a sophomore may feel more confident</p>
<p>in themselves and could be stronger students—hence, they take it earlier than</p>
<p>some of their peers. Whereas for juniors, there are a larger amount of people</p>
<p>overall and this includes those who may be slightly weaker in these</p>
<p>types of exams, but feel like they still need to take it before they graduate.</p>
<p>Do these findings apply to other students outside of the respondents? It turns</p>
<p>out, yes! Looking at the data published by the CollegeBoard, we see these</p>
<p>trends almost exactly match up</p>
<p>(link:<a href="https://reports.collegeboard.org/media/pdf/ap-score-distributions-for-specific-student-grade-level-groups-2022.pdf" class="uri">https://reports.collegeboard.org/media/pdf/ap-score-distributions-for-specific-student-grade-level-groups-2022.pdf</a>):</p>
<p><img src="pic1.jpeg" class="img-fluid"></p>
<p>Even though significantly more juniors <em>took</em> the exam <span class="math inline">\((N=1,872,496)\)</span> ,</p>
<p>a higher proportion of sophomores scored a 5 (<span class="math inline">\(25.69\%\)</span> vs.&nbsp;<span class="math inline">\(23.87\%\)</span>).</p>
<p>Does this mean you won’t get a 5 because you’re a junior? No!</p>
<p>Of course it’s more complicated than that and it likely depends more on</p>
<p>how much effort you yourself put it, but this is an interesting insight</p>
<p>that the data helped to reveal.</p>
<p>So clearly, we’re interested in scores, as it’s a solid way to</p>
<p>quantify performance, even if it’s not always perfect. Is there other</p>
<p>variables that we want to examine? Another factor that might be more solid</p>
<p>than grade level could be preparedness for the exam. One variable we</p>
<p>gathered data on is the level of perceived preparedness by the teachers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>teach.prep, <span class="at">y =</span> SCORE)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Scatterplot of teacher preparedness vs. score"</span>,</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Teacher Prep Rating"</span>,</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Exam Score"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>g2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using alpha, which makes points more transparent with less <em>overlap</em>, we see</p>
<p>that there could be some relationship. Points are more solid for scores of</p>
<p>5 when the preparedness rating is higher, indicating greater frequency of</p>
<p>occurrence (more students who got an exam score of 5 reported</p>
<p>a score of 8, 9, or 10 the most for how well their teacher prepared them). We</p>
<p>can also see this somewhat with the trend line, as it has a negative relationship</p>
<p>(slope) with score for small values of teaching rating but then it increases</p>
<p>at the midway point, which is exactly what we might expect!</p>
<p>At this point, there are a few more questions we might have to dive deeper on.</p>
<p>I finish this section by presenting some final visualizations for these</p>
<p>questions:</p>
<p><strong>Is there any relationship between how the student feels overall #in terms of preparedness vs.&nbsp;how well their teacher prepared them?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>g3 <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>teach.prep, <span class="at">y=</span>overall.prep)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>()</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>g3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 10 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What other classes are students taking, and do these have some relationship with how well they scored on the exam?</strong></p>
<p>We know APUSH is a history class—no arguments there! Since other</p>
<p>history use much of the same course/exam format and government classes</p>
<p>are sort of in the same ballpark of “studying one’s country,” they</p>
<p>may have some correlation with performance in APUSH.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Let's compare history/govt. vs. non-history/govt. first</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>d2_good_courses <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">good.course =</span> <span class="fu">as.integer</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>      <span class="fu">grepl</span>(<span class="st">"[Hh]istory|[Ee]uro|[Ww]orld|[Gg]ov"</span>, other.courses, <span class="at">ignore.case =</span> <span class="cn">TRUE</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>d2_good_courses_only <span class="ot">=</span> d2_good_courses <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(good.course <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">=</span> d2_good_courses_only <span class="sc">%&gt;%</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> SCORE)) <span class="sc">+</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">3</span>,               </span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">name      =</span> <span class="st">"Percentage of observations (%)"</span>,</span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand    =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))</span>
<span id="cb28-24"><a href="#cb28-24" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-25"><a href="#cb28-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-26"><a href="#cb28-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">x    =</span> <span class="st">"Exam Scores"</span>,</span>
<span id="cb28-27"><a href="#cb28-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scores of those taking other history/govt classes (%)"</span></span>
<span id="cb28-28"><a href="#cb28-28" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-29"><a href="#cb28-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb28-30"><a href="#cb28-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-31"><a href="#cb28-31" aria-hidden="true" tabindex="-1"></a>g4</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The dot-dot notation (`..count..`) was deprecated in ggplot2 3.4.0.
ℹ Please use `after_stat(count)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>d2_other_courses_only <span class="ot">=</span> d2_good_courses <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(good.course <span class="sc">==</span> <span class="dv">0</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>g4_2 <span class="ot">=</span> d2_other_courses_only <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> SCORE)) <span class="sc">+</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">3</span>,               </span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">"white"</span>,</span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">alpha =</span> <span class="fl">0.7</span></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">name      =</span> <span class="st">"Percentage of observations (%)"</span>,</span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand    =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))</span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x    =</span> <span class="st">"Exam Scores"</span>,</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Scores of those NOT taking other history/govt classes (%)"</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>g4_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>score.diff<span class="fl">.3</span> <span class="ot">=</span> <span class="fu">mean</span>(d2_good_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">-</span> <span class="fu">mean</span>(d2_other_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">3</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>score.diff<span class="fl">.4</span> <span class="ot">=</span> <span class="fu">mean</span>(d2_good_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">4</span>) <span class="sc">-</span> <span class="fu">mean</span>(d2_other_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>score.diff<span class="fl">.5</span> <span class="ot">=</span> <span class="fu">mean</span>(d2_good_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>) <span class="sc">-</span> <span class="fu">mean</span>(d2_other_courses_only<span class="sc">$</span>SCORE <span class="sc">==</span> <span class="dv">5</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>good.score.diff <span class="ot">=</span> <span class="fu">c</span>(score.diff<span class="fl">.3</span><span class="sc">*</span><span class="dv">100</span>, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                    score.diff<span class="fl">.4</span><span class="sc">*</span><span class="dv">100</span>, </span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                    score.diff<span class="fl">.5</span><span class="sc">*</span><span class="dv">100</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>score.diff.df <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">x=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>), <span class="at">y=</span>good.score.diff)</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>g4_3 <span class="ot">=</span> score.diff.df <span class="sc">%&gt;%</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="fu">factor</span>(x), <span class="at">y=</span>y)) <span class="sc">+</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>, </span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">name =</span> <span class="st">"Exam Scores"</span>) <span class="sc">+</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">name =</span> <span class="st">"Difference (%)"</span>) <span class="sc">+</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Proportional Difference in Scores (hist/govt. minus non-hist/govt.)"</span>) <span class="sc">+</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>g4_3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Interesting, so if we only look at the proportion of 5s, what class(es) will be</p>
<p>associated with it the most, i.e.&nbsp;what other class are people taking that will</p>
<p>show up the most when we filter by only those who got 5s?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>d2_onlyfives <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(SCORE <span class="sc">==</span> <span class="dv">5</span>)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(d2_onlyfives<span class="sc">$</span>other.courses)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Computer Science A"                                                                                                               
 [2] "Calculus AB, Chemistry, Environmental Science, Statistics"                                                                        
 [3] "Computer Science Principles, Precalculus, Spanish Language and Culture, Statistics"                                               
 [4] ""                                                                                                                                 
 [5] "Art History, Precalculus"                                                                                                         
 [6] "Calculus AB, Chemistry, English Language and Composition, Spanish Language and Culture"                                           
 [7] "Biology, Calculus BC, English Language and Composition"                                                                           
 [8] "Computer Science Principles"                                                                                                      
 [9] "Biology, English Literature and Composition, Spanish Language and Culture, Statistics"                                            
[10] "Chemistry, English Language and Composition, Statistics"                                                                          
[11] "Chemistry, English Language and Composition, Physics C: Electricity and Magnetism, Physics C: Mechanics, Research, Statistics"    
[12] "Biology, Computer Science Principles, English Language and Composition"                                                           
[13] "English Language and Composition, Environmental Science, Physics 1: Algebra Based, Precalculus"                                   
[14] "Biology, English Language and Composition"                                                                                        
[15] "Calculus AB"                                                                                                                      
[16] "Computer Science A, Statistics"                                                                                                   
[17] "Computer Science A, English Language and Composition"                                                                             
[18] "Comparative Government and Politics, English Language and Composition, Physics C: Electricity and Magnetism, Physics C: Mechanics"
[19] "Chemistry, English Language and Composition, Psychology"                                                                          
[20] "English Language and Composition"                                                                                                 
[21] "Biology, Calculus BC, English Language and Composition, French Language and Culture"                                              
[22] "Computer Science Principles, English Language and Composition"                                                                    
[23] "World History: Modern"                                                                                                            
[24] "English Literature and Composition, Precalculus"                                                                                  
[25] "Biology, Computer Science A"                                                                                                      
[26] "Comparative Government and Politics, United States Government and Politics"                                                       
[27] "English Language and Composition, Physics 1: Algebra Based, Precalculus"                                                          
[28] "Calculus BC, Physics C: Mechanics"                                                                                                
[29] "Chinese Language and Culture, Precalculus"                                                                                        
[30] "English Language and Composition, Spanish Language and Culture"                                                                   
[31] "Chemistry, English Language and Composition, Psychology, Research"                                                                </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>courses <span class="ot">=</span> <span class="fu">c</span>(</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science A"</span>,</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Calculus AB, Chemistry, Environmental Science, Statistics"</span>,</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science Principles, Precalculus, Spanish Language and Culture, Statistics"</span>,</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">""</span>,</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Art History, Precalculus"</span>,</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Calculus AB, Chemistry, English Language and Composition, Spanish Language and Culture"</span>,</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, Calculus BC, English Language and Composition"</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science Principles"</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, English Literature and Composition, Spanish Language and Culture, Statistics"</span>,</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chemistry, English Language and Composition, Statistics"</span>,</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chemistry, English Language and Composition, Physics C: Electricity and Magnetism, Physics C: Mechanics, Research, Statistics"</span>,</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, Computer Science Principles, English Language and Composition"</span>,</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a>  <span class="st">"English Language and Composition, Environmental Science, Physics 1: Algebra Based, Precalculus"</span>,</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, English Language and Composition"</span>,</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Calculus AB"</span>,</span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science A, Statistics"</span>,</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science A, English Language and Composition"</span>,</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Comparative Government and Politics, English Language and Composition, Physics C: Electricity and Magnetism, Physics C: Mechanics"</span>,</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chemistry, English Language and Composition, Psychology"</span>,</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">"English Language and Composition"</span>,</span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, Calculus BC, English Language and Composition, French Language and Culture"</span>,</span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Computer Science Principles, English Language and Composition"</span>,</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>  <span class="st">"World History: Modern"</span>,</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>  <span class="st">"English Literature and Composition, Precalculus"</span>,</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Biology, Computer Science A"</span>,</span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Comparative Government and Politics, United States Government and Politics"</span>,</span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>  <span class="st">"English Language and Composition, Physics 1: Algebra Based, Precalculus"</span>,</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Calculus BC, Physics C: Mechanics"</span>,</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chinese Language and Culture, Precalculus"</span>,</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a>  <span class="st">"English Language and Composition, Spanish Language and Culture"</span>,</span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Chemistry, English Language and Composition, Psychology, Research"</span></span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-36"><a href="#cb36-36" aria-hidden="true" tabindex="-1"></a>split_list <span class="ot">=</span> <span class="fu">strsplit</span>(courses, <span class="st">","</span>)</span>
<span id="cb36-37"><a href="#cb36-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-38"><a href="#cb36-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-39"><a href="#cb36-39" aria-hidden="true" tabindex="-1"></a>all_names <span class="ot">=</span> <span class="fu">trimws</span>(<span class="fu">unlist</span>(split_list))</span>
<span id="cb36-40"><a href="#cb36-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-41"><a href="#cb36-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-42"><a href="#cb36-42" aria-hidden="true" tabindex="-1"></a>all_names <span class="ot">=</span> all_names[all_names <span class="sc">!=</span> <span class="st">""</span>]</span>
<span id="cb36-43"><a href="#cb36-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-44"><a href="#cb36-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-45"><a href="#cb36-45" aria-hidden="true" tabindex="-1"></a>unique_courses <span class="ot">=</span> <span class="fu">sort</span>(<span class="fu">unique</span>(all_names))</span>
<span id="cb36-46"><a href="#cb36-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-47"><a href="#cb36-47" aria-hidden="true" tabindex="-1"></a>unique_courses</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Art History"                          
 [2] "Biology"                              
 [3] "Calculus AB"                          
 [4] "Calculus BC"                          
 [5] "Chemistry"                            
 [6] "Chinese Language and Culture"         
 [7] "Comparative Government and Politics"  
 [8] "Computer Science A"                   
 [9] "Computer Science Principles"          
[10] "English Language and Composition"     
[11] "English Literature and Composition"   
[12] "Environmental Science"                
[13] "French Language and Culture"          
[14] "Physics 1: Algebra Based"             
[15] "Physics C: Electricity and Magnetism" 
[16] "Physics C: Mechanics"                 
[17] "Precalculus"                          
[18] "Psychology"                           
[19] "Research"                             
[20] "Spanish Language and Culture"         
[21] "Statistics"                           
[22] "United States Government and Politics"
[23] "World History: Modern"                </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>keywords <span class="ot">=</span> unique_courses</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>hits_per_kw <span class="ot">&lt;-</span> <span class="fu">sapply</span>(keywords, <span class="cf">function</span>(k) {</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">str_detect</span>(d2_onlyfives<span class="sc">$</span>other.courses, </span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                 <span class="fu">regex</span>(k, <span class="at">ignore_case =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>d2_onlyfives_course_count <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">course =</span> <span class="fu">names</span>(hits_per_kw),</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">count =</span> <span class="fu">as.integer</span>(hits_per_kw),</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">row.names =</span> <span class="cn">NULL</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">stringsAsFactors =</span> <span class="cn">FALSE</span>)</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d2_onlyfives_course_count)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        course count
1                  Art History     1
2                      Biology     7
3                  Calculus AB     3
4                  Calculus BC     3
5                    Chemistry     6
6 Chinese Language and Culture     1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>d2_good_courses_only_sorted <span class="ot">=</span> d2_onlyfives_course_count <span class="sc">%&gt;%</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(count))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(d2_good_courses_only_sorted)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            course count
1 English Language and Composition    17
2                          Biology     7
3                        Chemistry     6
4      Computer Science Principles     6
5                      Precalculus     6
6                       Statistics     6</code></pre>
</div>
</div>
<p>English Language and Composition is at the top and appears to far exceed</p>
<p>any other course. This, of course, doesn’t necessarily mean that taking this</p>
<p>class will get you a 5 on the exam; it just happens that those who got a 5</p>
<p>took it as another class the most vs.&nbsp;any other class. Still, it does make some</p>
<p>degree of sense and one might be able to draw some arguments on the</p>
<p>usefulness of skills (writing, analyzing text, etc.) between APUSH and English</p>
<p>Language &amp; Composition.</p>
<p><strong>Expected vs.&nbsp;Actual perceived difficulty (before and after</strong></p>
<p><strong>taking the course/exam)</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>g5 <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>expected.diff, <span class="at">y=</span>overall.diff))<span class="sc">+</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>() <span class="sc">+</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Expected vs. Actual Difficulty Rating for APUSH"</span>,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"(*transparency factor alpha = 0.4 applied; darker</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="st">       points = greater overlap in data)"</span>,</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Expected Rating (1-10)"</span>,</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Actual Rating (1-10)"</span>)</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>g5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using method = 'loess' and formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Relationship appears positive, except at around 7, where there is a dip.</p>
<p><strong>Use of AI as a learning tool vs.&nbsp;Score</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ai.indicator =</span> <span class="fu">ifelse</span>(ai <span class="sc">==</span> <span class="st">"Yes"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>d2_ai <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ai.indicator <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>d2_no_ai <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(ai.indicator <span class="sc">==</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>g6 <span class="ot">=</span> d2_ai <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>SCORE)) <span class="sc">+</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Score distribution for students using AI as Learning Tool"</span>,</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Exam Score"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>g6</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>g6_2 <span class="ot">=</span> d2_ai <span class="sc">%&gt;%</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> SCORE)) <span class="sc">+</span></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">3</span>,               </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">name      =</span> <span class="st">"Percentage of students obtaining score"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand    =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x    =</span> <span class="st">"Exam Scores"</span>,</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Score distribution for AI-using students (%)"</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-16"><a href="#cb46-16" aria-hidden="true" tabindex="-1"></a>g6_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>g7 <span class="ot">=</span> d2_no_ai <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>SCORE)) <span class="sc">+</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">3</span>, <span class="at">fill =</span> <span class="st">"firebrick1"</span>) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Score distribution for students NOT using AI as tool"</span>,</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Exam Score"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frequency"</span>)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>g7</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>g7_2 <span class="ot">=</span> d2_no_ai <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> SCORE)) <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">aes</span>(<span class="at">y =</span> ..count.. <span class="sc">/</span> <span class="fu">sum</span>(..count..) <span class="sc">*</span> <span class="dv">100</span>),</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">bins =</span> <span class="dv">3</span>,               </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill =</span> <span class="st">"firebrick1"</span>) <span class="sc">+</span></span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(</span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">name      =</span> <span class="st">"Percentage of students obtaining score"</span>,</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">expand    =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.05</span>))</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-12"><a href="#cb48-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">x    =</span> <span class="st">"Exam Scores"</span>,</span>
<span id="cb48-13"><a href="#cb48-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Score distribution for non-AI using students (%)"</span></span>
<span id="cb48-14"><a href="#cb48-14" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb48-15"><a href="#cb48-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-16"><a href="#cb48-16" aria-hidden="true" tabindex="-1"></a>g7_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>g6_2 <span class="sc">+</span> g7_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Even though AI-using students have less observations than non-AI using</p>
<p>students, it appears that the distribution of scores is nearly identical, possibly</p>
<p>suggesting that using it as a learning tool for APUSH does not have</p>
<p>a significant impact on score, either positively or negatively. However, one</p>
<p>should also keep in mind the possibility of response bias—some students</p>
<p>who did use AI may have said they didn’t and some who didn’t may have</p>
<p>said they did. Possible reasons include forgetfulness and social desirability</p>
<p>bias, e.g.&nbsp;wanting to appear as only relying on oneself to have obtained the</p>
<p>score rather than using AI. Fear of academic consequences/retaliation/</p>
<p>disciplinary measures is still possible but much less likely to be a</p>
<p>possible reason because</p>
<p>(1) The survey was anonymous and could not be traced back to anyone.</p>
<p>(2) Even if it wasn’t, most people would’ve only been traced back to their online</p>
<p>accounts (which might not be easily connected to a real person)</p>
<p>(3) Most importantly, use of AI as a <em>learning tool</em> was the question being</p>
<p>asked, not as an exam tool. Most teachers permit it as a learning tool.</p>
</section>
<section id="iv.-linear-models-and-inferential-statistics" class="level1">
<h1>IV. Linear Models and Inferential Statistics</h1>
<p><strong>Linear Modelling</strong></p>
<p>Can we create a regression model that relates scores to these</p>
<p>multiple variables? Which model performs better when we include/remove</p>
<p>variables?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Exam Score vs. Teacher preparation score</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Quadratic regression might be appropriate here</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">=</span> <span class="fu">lm</span>(SCORE <span class="sc">~</span> teach.prep <span class="sc">+</span> <span class="fu">I</span>(teach.prep<span class="sc">^</span><span class="dv">2</span>), <span class="at">data =</span> d2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SCORE ~ teach.prep + I(teach.prep^2), data = d2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6752 -0.4210  0.3248  0.5193  0.7152 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      5.00515    0.68977   7.256 9.14e-10 ***
teach.prep      -0.25066    0.22507  -1.114    0.270    
I(teach.prep^2)  0.02177    0.01662   1.310    0.195    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6864 on 60 degrees of freedom
  (10 observations deleted due to missingness)
Multiple R-squared:  0.04851,   Adjusted R-squared:  0.0168 
F-statistic:  1.53 on 2 and 60 DF,  p-value: 0.225</code></pre>
</div>
</div>
<p>Looks like there’s a lot of variability that’s not being captured by the model</p>
<p>(<span class="math inline">\(r^2 \approx 0.04851\)</span>). This might be because a lot of people can still get 5s</p>
<p>by preparing themselves. Does using overall preparation give better</p>
<p>estimates and model?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">=</span> <span class="fu">lm</span>(SCORE <span class="sc">~</span> overall.prep, <span class="at">data =</span> d2)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SCORE ~ overall.prep, data = d2)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6717 -0.4956  0.3283  0.4164  1.0327 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.87926    0.25125  15.440   &lt;2e-16 ***
overall.prep  0.08804    0.03437   2.562   0.0125 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6448 on 71 degrees of freedom
Multiple R-squared:  0.0846,    Adjusted R-squared:  0.07171 
F-statistic: 6.562 on 1 and 71 DF,  p-value: 0.01254</code></pre>
</div>
</div>
<p>Better (adjusted <span class="math inline">\(r^2 = 0.07171 &gt; 0.04851)\)</span>, but maybe there is room</p>
<p>for improvement.</p>
<p>Let’s think about what other factors could affect the score (course/exam</p>
<p>difficulty, time management during exam). We should flip difficulty</p>
<p>to get it on the same scale as the other two because higher ratings for prep</p>
<p>and time management is what we might expect for higher scores</p>
<p>but higher ratings for difficulty might expect lower scores.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>d2_reordered <span class="ot">=</span> d2 <span class="sc">%&gt;%</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">overall.diff =</span> <span class="dv">11</span> <span class="sc">-</span> overall.diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>m3 <span class="ot">=</span> <span class="fu">lm</span>(SCORE <span class="sc">~</span> overall.prep <span class="sc">+</span> </span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>          overall.diff <span class="sc">+</span> </span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>          Time.management.during.exam, <span class="at">data =</span> d2_reordered)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = SCORE ~ overall.prep + overall.diff + Time.management.during.exam, 
    data = d2_reordered)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6103 -0.5109  0.2791  0.4818  1.0291 

Coefficients:
                            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  3.89995    0.32051  12.168   &lt;2e-16 ***
overall.prep                 0.09598    0.03805   2.522    0.014 *  
overall.diff                -0.04631    0.04353  -1.064    0.291    
Time.management.during.exam  0.02134    0.03815   0.559    0.578    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6485 on 69 degrees of freedom
Multiple R-squared:  0.1002,    Adjusted R-squared:  0.06108 
F-statistic: 2.561 on 3 and 69 DF,  p-value: 0.06188</code></pre>
</div>
</div>
<p>Looks like it improved but not by much. Moreover, even though</p>
<p><span class="math inline">\(r^2 = 0.1002\)</span>, adjusted <span class="math inline">\(r^2\)</span>, which penalizes for unhelpful predictors,</p>
<p>actually decreased. This is overall OK— <span class="math inline">\(r^2\)</span> isn’t everything and it just</p>
<p>shows that we can’t capture all of the variability in exam score well,</p>
<p>likely due to the predictors being subjective measures reported voluntarily</p>
<p>by students. It could very well be that one student’s interpretation of a</p>
<p>rating of 10 for the difficulty of course/exam is different than another</p>
<p>student’s rating, and hence there is a mismatch that affects the model.</p>
<p>This is supported by the fact that in our visualizations, we could see the</p>
<p>data followed some trends that could be captured by some curve,</p>
<p>but assumptions for linear models might not have been fully met.</p>
<p>In a perfect world, we might have a much higher adjusted <span class="math inline">\(r^2\)</span> and a</p>
<p>clearer relationship between score and the predictors, but it’s enough</p>
<p>that we were able to see some relationship in the frequency of the</p>
<p>data (e.g.&nbsp;<em>more</em> students who rated some predictor highly scored better).</p>
<p><strong>Inference on a population</strong></p>
<p>Is there statistically significant evidence, based on our sample asking</p>
<p>the corresponding questions, that the difference in means of all</p>
<p>course taking students in their estimation of the expected difficulty vs.</p>
<p>the actual difficulty of the course is not the same (e.g.&nbsp;misjudged the</p>
<p>difficulty)?</p>
<p>Some possible options are available, especially a paired t-test, but we would</p>
<p>have to check certain assumptions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2<span class="sc">$</span>expected.diff) <span class="sc">&gt;</span> <span class="dv">30</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2<span class="sc">$</span>overall.diff) <span class="sc">&gt;</span> <span class="dv">30</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>df_inf <span class="ot">=</span> <span class="fu">data.frame</span>(<span class="at">a =</span> d2<span class="sc">$</span>expected.diff, <span class="at">b =</span> d2<span class="sc">$</span>overall.diff)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>g_inf <span class="ot">=</span> df_inf <span class="sc">%&gt;%</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>a<span class="sc">-</span>b)) <span class="sc">+</span> </span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of differences in expected vs. actual</span></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a><span class="st">       difficulty ratings"</span>,</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Difficulty Rating (1-10)"</span>,</span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Number of Students (Frequency)"</span>)</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>g_inf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Not only is <span class="math inline">\(n\)</span> large, but the distribution of differences also looks fairly</p>
<p>normal. From the official national dataset, we know that <span class="math inline">\(N &gt; 400,000\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2<span class="sc">$</span>expected.diff) <span class="sc">==</span> <span class="fu">length</span>(d2<span class="sc">$</span>overall.diff)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(d2<span class="sc">$</span>expected.diff) <span class="sc">&lt;</span> (<span class="dv">1</span><span class="sc">/</span><span class="dv">10</span>)<span class="sc">*</span><span class="dv">400000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>Therefore, the sample is approximately independent. The only condition</p>
<p>we can’t be sure of is representative sampling, so we would only be able</p>
<p>to more confidently generalize to populations with similar characteristics</p>
<p>as survey respondents. A smaller issue is the fact that we are using an</p>
<p>ordinal scale, but we chose this test over something like the Wilcox</p>
<p>Ranked-Sign Test because normality condition is well met and difference</p>
<p>between different intervals is not large in the context of our problem which</p>
<p>uses a 10 point scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(<span class="at">x=</span>df_inf<span class="sc">$</span>a, <span class="at">y=</span>df_inf<span class="sc">$</span>b, <span class="at">alternative =</span> <span class="st">"two.sided"</span>,</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>       <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  df_inf$a and df_inf$b
t = 5.7448, df = 72, p-value = 2.05e-07
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.9929127 2.0481832
sample estimates:
mean difference 
       1.520548 </code></pre>
</div>
</div>
<p>Since <span class="math inline">\(p \approx 2.05 \times 10^{-7}\)</span>, we have statistically significant evidence at every</p>
<p>reasonable alpha level (<span class="math inline">\(\alpha = 0.01, 0.05, 0.10\)</span>) that the difference in means</p>
<p>is not equal to 0 (more students may have misjudged the difficulty).</p>
</section>
<section id="v.-further-work-and-interactives" class="level1">
<h1>V. Further work and Interactives</h1>
<p><strong>To what extent did the 8 themes of APUSH show up on the exam, on</strong></p>
<p><strong>a scale of 1-5?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>df_themes <span class="ot">=</span> d2 <span class="sc">%&gt;%</span> </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">pivot_longer</span>(</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">cols =</span> theme1<span class="sc">:</span>theme8,</span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">names_to =</span> <span class="st">"theme"</span>,</span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">values_to =</span> <span class="st">"exam_freq"</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>g_anim1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_themes, <span class="fu">aes</span>(<span class="at">x =</span> exam_freq)) <span class="sc">+</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill     =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">color    =</span> <span class="st">"black"</span>,</span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">width    =</span> <span class="fl">0.8</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">minor_breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">x     =</span> <span class="st">"Rating (1 = Never; 5 = Very Frequently)"</span>,</span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">y     =</span> <span class="st">"Number of Students"</span>,</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"How frequently did themes 1-8 show up on the exam? ({closest_state})"</span></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb70-21"><a href="#cb70-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transition_states</span>(</span>
<span id="cb70-22"><a href="#cb70-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">states         =</span> theme,</span>
<span id="cb70-23"><a href="#cb70-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">transition_length =</span> <span class="dv">2</span>,   <span class="co"># how many frames it takes to tween between topics</span></span>
<span id="cb70-24"><a href="#cb70-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_length     =</span> <span class="dv">1</span>    <span class="co"># how many frames to hold each topic</span></span>
<span id="cb70-25"><a href="#cb70-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb70-26"><a href="#cb70-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ease_aes</span>(<span class="st">"sine-in-out"</span>)   <span class="co"># smoother easing between states</span></span>
<span id="cb70-27"><a href="#cb70-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-28"><a href="#cb70-28" aria-hidden="true" tabindex="-1"></a>g_anim1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-34-1.gif" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>anim_output <span class="ot">&lt;-</span> <span class="fu">animate</span>(</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  g_anim1,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nframes =</span> <span class="dv">80</span>,   <span class="co"># total frames (8 states × 10 frames per state roughly)</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">fps     =</span> <span class="dv">10</span>,   <span class="co"># 10 frames per second → ~8 seconds animation</span></span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">width   =</span> <span class="dv">600</span>,</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">height  =</span> <span class="dv">400</span></span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview in RStudio Viewer or save to disk:</span></span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>anim_output</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a><span class="fu">anim_save</span>(<span class="st">"theme_freq_animation.gif"</span>, <span class="at">animation =</span> anim_output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>How difficult are the benchmark “thinking skills” of the course,</strong></p>
<p><strong>on a scale of 1-5?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>df_themes <span class="ot">=</span> d2 <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">pivot_longer</span>(</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">cols =</span> <span class="fu">c</span>(Developments.and.Processes, Sourcing.and.Citation,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>               Claim.and.Evidence.in.Sources, Contextualization,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>               Making.Connections, Argumentation),</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">names_to =</span> <span class="st">"skills"</span>,</span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">values_to =</span> <span class="st">"difficulty"</span></span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>g_anim2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(df_themes, <span class="fu">aes</span>(<span class="at">x =</span> difficulty)) <span class="sc">+</span></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">fill     =</span> <span class="st">"steelblue"</span>,</span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">color    =</span> <span class="st">"black"</span>,</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">width    =</span> <span class="fl">0.8</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>, <span class="at">minor_breaks =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">x     =</span> <span class="st">"Rating (1 = Easy; 5 = Hard)"</span>,</span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>    <span class="at">y     =</span> <span class="st">"Number of Students"</span>,</span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Benchmark 'thinking skills' difficulty ({closest_state})"</span></span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transition_states</span>(</span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">states         =</span> skills,</span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">transition_length =</span> <span class="dv">2</span>,   <span class="co"># how many frames it takes to tween between topics</span></span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a>    <span class="at">state_length     =</span> <span class="dv">2</span>    <span class="co"># how many frames to hold each topic</span></span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ease_aes</span>(<span class="st">"sine-in-out"</span>)   <span class="co"># smoother easing between states</span></span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-30"><a href="#cb72-30" aria-hidden="true" tabindex="-1"></a>g_anim2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="apush-data-anal_files/figure-html/unnamed-chunk-36-1.gif" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>anim_output <span class="ot">&lt;-</span> <span class="fu">animate</span>(</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  g_anim2,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">nframes =</span> <span class="dv">80</span>,   <span class="co"># total frames (8 states × 10 frames per state roughly)</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">fps     =</span> <span class="dv">10</span>,   <span class="co"># 10 frames per second → ~8 seconds animation</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">width   =</span> <span class="dv">600</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">height  =</span> <span class="dv">400</span></span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Preview in RStudio Viewer or save to disk:</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>anim_output</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a><span class="fu">anim_save</span>(<span class="st">"skill_diff_animation.gif"</span>, <span class="at">animation =</span> anim_output)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>